services:
  backend:
    build:
      context: ./Backend
    ports:
      - "4000:4000"
    env_file:
      - .env

  python-backend:
    build:
      context: ./Backend-Python
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"